export const programs = [
  {
    id: 1, 
    type: "Youth Empowerment",
    length: "4 week",
    date: "May 21 - June 15",
    enrolled: 0,
  },
  {
    id: 2, 
    type: "Youth Empowerment",
    length: "4 week",
    date: "June 18 - July 13",
    enrolled: 0,
  },
  {
    id: 3, 
    type: "Youth Empowerment",
    length: "4 week",
    date: "July 16 - August 10",
    enrolled: 0,
  },
  {
    id: 4, 
    type: "Youth Empowerment",
    length: "4 week",
    date: "July 30 - August 24",
    enrolled: 0,
  },
  {
    id: 5, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "May 21 - June 1",
    enrolled: 0,
  },
  {
    id: 6, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "June 4 - June 15",
    enrolled: 0,
  },
  {
    id: 7, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "June 18 - June 29",
    enrolled: 0,
  },
  {
    id: 8, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "July 2 - July 13",
    enrolled: 0,
  },
  {
    id: 9, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "July 16 - July 27",
    enrolled: 0,
  },
  {
    id: 10, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "July 30 - August 10",
    enrolled: 0,
  },
  {
    id: 11, 
    type: "Youth Empowerment",
    length: "2 week",
    date: "August 13 - August 24",
    enrolled: 0,
  },
  {
    id: 12, 
    type: "Health Innovation",
    length: "2 week",
    date: "May 21 - June 1",
    enrolled: 0,
  },
  {
    id: 13, 
    type: "Health Innovation",
    length: "2 week",
    date: "June 4 - June 15",
    enrolled: 0,
  },
  {
    id: 14, 
    type: "Health Innovation",
    length: "2 week",
    date: "June 18 - June 29",
    enrolled: 0,
  },
  {
    id: 15, 
    type: "Health Innovation",
    length: "2 week",
    date: "July 2 - July 13",
    enrolled: 0,
  },
  {
    id: 16, 
    type: "Health Innovation",
    length: "2 week",
    date: "July 16 - July 27",
    enrolled: 0,
  },
  {
    id: 17, 
    type: "Health Innovation",
    length: "2 week",
    date: "July 30 - August 10",
    enrolled: 0,
  }
];
